site_name: Jeu interractif - Seras-tu à l'heure ?
site_url: https://<matischiavuzzo>.github.io/<game>/

nav:
  - Accueil: index.md
  - Regles du jeu: ./pages/regles.md
  - Jouer: ./pages/jeu.html
  - Sources: ./pages/sources.md
  - Documentation: ./pages/documentation.md

theme:
  name: material
  logo: ./image/logo.png
  favicon: ./image/logo.png
  palette:
    primary: deep purple
    accent: deep purple
  features:
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<matis.chiavuzzo@laposte.net>
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/matis-chiavuzzo-581044356/
  generator: false

copyright: © Matis Chiavuzzo & Ninon Tuaillon | Dernière mise à jour - Janvier 2026


extra_css:
  - ./css/extra.css
