site_name: Jeu interractif
site_url: https://projet-jeu-interractif.github.io/game/

nav:
  - Accueil: index.md
  - Installation: installation.md
  - Utilisation: utilisation.md

nav:
  - Accueil: index.md
  - Regles du jeu: ./pages/regles.md
  - Jeu: ./pages/jeu.html

theme: mkdocs
theme:
  name: material

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite
